apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://helm.datadoghq.com
    chart: datadog
    targetRevision: 3.120.0

    helm:
      values: |
        datadog:
          site: datadoghq.com
          apiKeyExistingSecret: datadog-secret

          clusterName: onprem-gitops

          kubelet:
            useApiServer: true
            tlsVerify: false

          logs:
            enabled: true
            containerCollectAll: true

          apm:
            enabled: false

          processAgent:
            enabled: false

          tags:
            - env:dev
            - managed-by:argocd

        clusterAgent:
          enabled: true
          replicas: 2
          tokenExistingSecret: datadog-cluster-agent-token

  destination:
    server: https://kubernetes.default.svc
    namespace: datadog

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
