apiVersion: v2
name: datadog
description: Datadog GitOps Wrapper Chart
type: application
version: 0.1.0

dependencies:
  - name: datadog
    version: 3.120.0
    repository: https://helm.datadoghq.com
