datadog:
  site: datadoghq.com

  apiKeyExistingSecret: datadog-secret

  clusterName: onprem-gitops

  apm:
    enabled: false

  processAgent:
    enabled: false

  logs:
    enabled: true
    containerCollectAll: true

clusterAgent:
  enabled: true
