datadog:
  site: datadoghq.com

  apiKeyExistingSecret: datadog-secret

  clusterName: onprem-gitops

  kubelet:
    tlsVerify: false

  logs:
    enabled: true
    containerCollectAll: true

  apm:
    enabled: false

  processAgent:
    enabled: false

clusterAgent:
  enabled: true
